## Initializing A Tensor

In [1]:
import torch
x=torch.tensor([[1,2]])
y=torch.tensor([[1],[2]])

In [2]:
print(x.shape)
# torch.Size([1,2])  # one entity of two items
print(y.shape)
# torch.Size([2,1])  # two entity of one items
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x=torch.tensor([False,1,2.0])
print(x)
# tensor([0.,1.,2.])

tensor([0., 1., 2.])


In [4]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
torch.randint(low=0,high=10,size=(3,4))

tensor([[2, 3, 3, 6],
        [2, 1, 1, 1],
        [4, 7, 9, 5]])

In [7]:
torch.rand(3,4)

tensor([[0.6028, 0.6579, 0.2024, 0.7726],
        [0.9989, 0.9883, 0.2164, 0.7639],
        [0.0999, 0.7048, 0.3901, 0.6899]])

In [8]:
torch.randn((3,4))

tensor([[-0.1765, -0.7011,  0.0767, -1.0763],
        [-0.8187, -0.2086, -0.4634,  1.6801],
        [ 1.0824, -0.0577,  0.3495, -0.3925]])

In [9]:
import numpy as np
x=np.array([[10,20,30],[2,3,4]])
y=torch.tensor(x)
print(type(x),type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
